/*
 * This file is generated by jOOQ.
*/
package es.eci.catalog.model.tables.records;


import es.eci.catalog.model.tables.ItemImage_;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemImage_Record extends UpdatableRecordImpl<ItemImage_Record> implements Record8<Integer, Integer, String, String, Object, String[], String, Integer> {

    private static final long serialVersionUID = -1165636098;

    /**
     * Setter for <code>public.item_image_._id_</code>.
     */
    public void set_Id_(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.item_image_._id_</code>.
     */
    public Integer get_Id_() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.item_image_._item_id_</code>.
     */
    public void set_ItemId_(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.item_image_._item_id_</code>.
     */
    public Integer get_ItemId_() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.item_image_.alt_text_</code>.
     */
    public void setAltText_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.item_image_.alt_text_</code>.
     */
    public String getAltText_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.item_image_.image_</code>.
     */
    public void setImage_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.item_image_.image_</code>.
     */
    public String getImage_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.item_image_._search_</code>.
     */
    public void set_Search_(Object value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.item_image_._search_</code>.
     */
    public Object get_Search_() {
        return (Object) get(4);
    }

    /**
     * Setter for <code>public.item_image_._types_</code>.
     */
    public void set_Types_(String... value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.item_image_._types_</code>.
     */
    public String[] get_Types_() {
        return (String[]) get(5);
    }

    /**
     * Setter for <code>public.item_image_._last_modified_</code>.
     */
    public void set_LastModified_(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.item_image_._last_modified_</code>.
     */
    public String get_LastModified_() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.item_image_._version_</code>.
     */
    public void set_Version_(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.item_image_._version_</code>.
     */
    public Integer get_Version_() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, String, String, Object, String[], String, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, String, String, Object, String[], String, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ItemImage_.ITEM_IMAGE_._ID_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ItemImage_.ITEM_IMAGE_._ITEM_ID_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ItemImage_.ITEM_IMAGE_.ALT_TEXT_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ItemImage_.ITEM_IMAGE_.IMAGE_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field5() {
        return ItemImage_.ITEM_IMAGE_._SEARCH_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field6() {
        return ItemImage_.ITEM_IMAGE_._TYPES_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return ItemImage_.ITEM_IMAGE_._LAST_MODIFIED_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return ItemImage_.ITEM_IMAGE_._VERSION_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return get_Id_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return get_ItemId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAltText_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getImage_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value5() {
        return get_Search_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value6() {
        return get_Types_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return get_LastModified_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return get_Version_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemImage_Record value1(Integer value) {
        set_Id_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemImage_Record value2(Integer value) {
        set_ItemId_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemImage_Record value3(String value) {
        setAltText_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemImage_Record value4(String value) {
        setImage_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemImage_Record value5(Object value) {
        set_Search_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemImage_Record value6(String... value) {
        set_Types_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemImage_Record value7(String value) {
        set_LastModified_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemImage_Record value8(Integer value) {
        set_Version_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemImage_Record values(Integer value1, Integer value2, String value3, String value4, Object value5, String[] value6, String value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemImage_Record
     */
    public ItemImage_Record() {
        super(ItemImage_.ITEM_IMAGE_);
    }

    /**
     * Create a detached, initialised ItemImage_Record
     */
    public ItemImage_Record(Integer _Id_, Integer _ItemId_, String altText_, String image_, Object _Search_, String[] _Types_, String _LastModified_, Integer _Version_) {
        super(ItemImage_.ITEM_IMAGE_);

        set(0, _Id_);
        set(1, _ItemId_);
        set(2, altText_);
        set(3, image_);
        set(4, _Search_);
        set(5, _Types_);
        set(6, _LastModified_);
        set(7, _Version_);
    }
}
