/*
 * This file is generated by jOOQ.
*/
package es.eci.catalog.model.tables.records;


import es.eci.catalog.model.tables.Material_;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Material_Record extends UpdatableRecordImpl<Material_Record> implements Record8<Integer, Integer, Integer, Integer, Object, String[], String, Integer> {

    private static final long serialVersionUID = 147414614;

    /**
     * Setter for <code>public.material_._id_</code>.
     */
    public void set_Id_(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.material_._id_</code>.
     */
    public Integer get_Id_() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.material_._course_id_</code>.
     */
    public void set_CourseId_(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.material_._course_id_</code>.
     */
    public Integer get_CourseId_() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.material_.quantity_</code>.
     */
    public void setQuantity_(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.material_.quantity_</code>.
     */
    public Integer getQuantity_() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.material_.item_</code>.
     */
    public void setItem_(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.material_.item_</code>.
     */
    public Integer getItem_() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.material_._search_</code>.
     */
    public void set_Search_(Object value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.material_._search_</code>.
     */
    public Object get_Search_() {
        return (Object) get(4);
    }

    /**
     * Setter for <code>public.material_._types_</code>.
     */
    public void set_Types_(String... value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.material_._types_</code>.
     */
    public String[] get_Types_() {
        return (String[]) get(5);
    }

    /**
     * Setter for <code>public.material_._last_modified_</code>.
     */
    public void set_LastModified_(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.material_._last_modified_</code>.
     */
    public String get_LastModified_() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.material_._version_</code>.
     */
    public void set_Version_(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.material_._version_</code>.
     */
    public Integer get_Version_() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, Integer, Object, String[], String, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, Integer, Object, String[], String, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Material_.MATERIAL_._ID_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Material_.MATERIAL_._COURSE_ID_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Material_.MATERIAL_.QUANTITY_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Material_.MATERIAL_.ITEM_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field5() {
        return Material_.MATERIAL_._SEARCH_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field6() {
        return Material_.MATERIAL_._TYPES_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Material_.MATERIAL_._LAST_MODIFIED_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Material_.MATERIAL_._VERSION_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return get_Id_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return get_CourseId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getQuantity_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getItem_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value5() {
        return get_Search_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value6() {
        return get_Types_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return get_LastModified_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return get_Version_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Material_Record value1(Integer value) {
        set_Id_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Material_Record value2(Integer value) {
        set_CourseId_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Material_Record value3(Integer value) {
        setQuantity_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Material_Record value4(Integer value) {
        setItem_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Material_Record value5(Object value) {
        set_Search_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Material_Record value6(String... value) {
        set_Types_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Material_Record value7(String value) {
        set_LastModified_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Material_Record value8(Integer value) {
        set_Version_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Material_Record values(Integer value1, Integer value2, Integer value3, Integer value4, Object value5, String[] value6, String value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Material_Record
     */
    public Material_Record() {
        super(Material_.MATERIAL_);
    }

    /**
     * Create a detached, initialised Material_Record
     */
    public Material_Record(Integer _Id_, Integer _CourseId_, Integer quantity_, Integer item_, Object _Search_, String[] _Types_, String _LastModified_, Integer _Version_) {
        super(Material_.MATERIAL_);

        set(0, _Id_);
        set(1, _CourseId_);
        set(2, quantity_);
        set(3, item_);
        set(4, _Search_);
        set(5, _Types_);
        set(6, _LastModified_);
        set(7, _Version_);
    }
}
