/*
 * This file is generated by jOOQ.
*/
package es.eci.catalog.model.tables.records;


import es.eci.catalog.model.tables.SchedulingProcess_;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SchedulingProcess_Record extends UpdatableRecordImpl<SchedulingProcess_Record> implements Record8<Integer, String, String, String, Object, String[], String, Integer> {

    private static final long serialVersionUID = 609057820;

    /**
     * Setter for <code>public.scheduling_process_._id_</code>.
     */
    public void set_Id_(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.scheduling_process_._id_</code>.
     */
    public Integer get_Id_() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.scheduling_process_.name_</code>.
     */
    public void setName_(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.scheduling_process_.name_</code>.
     */
    public String getName_() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.scheduling_process_.cron_expression_</code>.
     */
    public void setCronExpression_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.scheduling_process_.cron_expression_</code>.
     */
    public String getCronExpression_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.scheduling_process_.script_</code>.
     */
    public void setScript_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.scheduling_process_.script_</code>.
     */
    public String getScript_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.scheduling_process_._search_</code>.
     */
    public void set_Search_(Object value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.scheduling_process_._search_</code>.
     */
    public Object get_Search_() {
        return (Object) get(4);
    }

    /**
     * Setter for <code>public.scheduling_process_._types_</code>.
     */
    public void set_Types_(String... value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.scheduling_process_._types_</code>.
     */
    public String[] get_Types_() {
        return (String[]) get(5);
    }

    /**
     * Setter for <code>public.scheduling_process_._last_modified_</code>.
     */
    public void set_LastModified_(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.scheduling_process_._last_modified_</code>.
     */
    public String get_LastModified_() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.scheduling_process_._version_</code>.
     */
    public void set_Version_(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.scheduling_process_._version_</code>.
     */
    public Integer get_Version_() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, Object, String[], String, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, Object, String[], String, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SchedulingProcess_.SCHEDULING_PROCESS_._ID_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SchedulingProcess_.SCHEDULING_PROCESS_.NAME_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SchedulingProcess_.SCHEDULING_PROCESS_.CRON_EXPRESSION_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SchedulingProcess_.SCHEDULING_PROCESS_.SCRIPT_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field5() {
        return SchedulingProcess_.SCHEDULING_PROCESS_._SEARCH_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field6() {
        return SchedulingProcess_.SCHEDULING_PROCESS_._TYPES_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SchedulingProcess_.SCHEDULING_PROCESS_._LAST_MODIFIED_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return SchedulingProcess_.SCHEDULING_PROCESS_._VERSION_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return get_Id_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCronExpression_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getScript_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value5() {
        return get_Search_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value6() {
        return get_Types_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return get_LastModified_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return get_Version_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchedulingProcess_Record value1(Integer value) {
        set_Id_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchedulingProcess_Record value2(String value) {
        setName_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchedulingProcess_Record value3(String value) {
        setCronExpression_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchedulingProcess_Record value4(String value) {
        setScript_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchedulingProcess_Record value5(Object value) {
        set_Search_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchedulingProcess_Record value6(String... value) {
        set_Types_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchedulingProcess_Record value7(String value) {
        set_LastModified_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchedulingProcess_Record value8(Integer value) {
        set_Version_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchedulingProcess_Record values(Integer value1, String value2, String value3, String value4, Object value5, String[] value6, String value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SchedulingProcess_Record
     */
    public SchedulingProcess_Record() {
        super(SchedulingProcess_.SCHEDULING_PROCESS_);
    }

    /**
     * Create a detached, initialised SchedulingProcess_Record
     */
    public SchedulingProcess_Record(Integer _Id_, String name_, String cronExpression_, String script_, Object _Search_, String[] _Types_, String _LastModified_, Integer _Version_) {
        super(SchedulingProcess_.SCHEDULING_PROCESS_);

        set(0, _Id_);
        set(1, name_);
        set(2, cronExpression_);
        set(3, script_);
        set(4, _Search_);
        set(5, _Types_);
        set(6, _LastModified_);
        set(7, _Version_);
    }
}
