/*
 * This file is generated by jOOQ.
*/
package es.eci.catalog.model.tables.records;


import es.eci.catalog.model.tables.SecurityAccessPrivilege_;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SecurityAccessPrivilege_Record extends UpdatableRecordImpl<SecurityAccessPrivilege_Record> implements Record10<Integer, Integer, String, Integer[], Integer[], Integer[], Object, String[], String, Integer> {

    private static final long serialVersionUID = -897192743;

    /**
     * Setter for <code>public.security_access_privilege_._id_</code>.
     */
    public void set_Id_(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.security_access_privilege_._id_</code>.
     */
    public Integer get_Id_() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.security_access_privilege_._security_role_id_</code>.
     */
    public void set_SecurityRoleId_(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.security_access_privilege_._security_role_id_</code>.
     */
    public Integer get_SecurityRoleId_() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.security_access_privilege_.name_</code>.
     */
    public void setName_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.security_access_privilege_.name_</code>.
     */
    public String getName_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.security_access_privilege_.operations_</code>.
     */
    public void setOperations_(Integer... value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.security_access_privilege_.operations_</code>.
     */
    public Integer[] getOperations_() {
        return (Integer[]) get(3);
    }

    /**
     * Setter for <code>public.security_access_privilege_.entities_</code>.
     */
    public void setEntities_(Integer... value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.security_access_privilege_.entities_</code>.
     */
    public Integer[] getEntities_() {
        return (Integer[]) get(4);
    }

    /**
     * Setter for <code>public.security_access_privilege_.attributes_</code>.
     */
    public void setAttributes_(Integer... value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.security_access_privilege_.attributes_</code>.
     */
    public Integer[] getAttributes_() {
        return (Integer[]) get(5);
    }

    /**
     * Setter for <code>public.security_access_privilege_._search_</code>.
     */
    public void set_Search_(Object value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.security_access_privilege_._search_</code>.
     */
    public Object get_Search_() {
        return (Object) get(6);
    }

    /**
     * Setter for <code>public.security_access_privilege_._types_</code>.
     */
    public void set_Types_(String... value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.security_access_privilege_._types_</code>.
     */
    public String[] get_Types_() {
        return (String[]) get(7);
    }

    /**
     * Setter for <code>public.security_access_privilege_._last_modified_</code>.
     */
    public void set_LastModified_(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.security_access_privilege_._last_modified_</code>.
     */
    public String get_LastModified_() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.security_access_privilege_._version_</code>.
     */
    public void set_Version_(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.security_access_privilege_._version_</code>.
     */
    public Integer get_Version_() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, String, Integer[], Integer[], Integer[], Object, String[], String, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, String, Integer[], Integer[], Integer[], Object, String[], String, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SecurityAccessPrivilege_.SECURITY_ACCESS_PRIVILEGE_._ID_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return SecurityAccessPrivilege_.SECURITY_ACCESS_PRIVILEGE_._SECURITY_ROLE_ID_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SecurityAccessPrivilege_.SECURITY_ACCESS_PRIVILEGE_.NAME_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer[]> field4() {
        return SecurityAccessPrivilege_.SECURITY_ACCESS_PRIVILEGE_.OPERATIONS_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer[]> field5() {
        return SecurityAccessPrivilege_.SECURITY_ACCESS_PRIVILEGE_.ENTITIES_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer[]> field6() {
        return SecurityAccessPrivilege_.SECURITY_ACCESS_PRIVILEGE_.ATTRIBUTES_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field7() {
        return SecurityAccessPrivilege_.SECURITY_ACCESS_PRIVILEGE_._SEARCH_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field8() {
        return SecurityAccessPrivilege_.SECURITY_ACCESS_PRIVILEGE_._TYPES_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return SecurityAccessPrivilege_.SECURITY_ACCESS_PRIVILEGE_._LAST_MODIFIED_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return SecurityAccessPrivilege_.SECURITY_ACCESS_PRIVILEGE_._VERSION_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return get_Id_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return get_SecurityRoleId_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer[] value4() {
        return getOperations_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer[] value5() {
        return getEntities_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer[] value6() {
        return getAttributes_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value7() {
        return get_Search_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value8() {
        return get_Types_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return get_LastModified_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return get_Version_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecurityAccessPrivilege_Record value1(Integer value) {
        set_Id_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecurityAccessPrivilege_Record value2(Integer value) {
        set_SecurityRoleId_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecurityAccessPrivilege_Record value3(String value) {
        setName_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecurityAccessPrivilege_Record value4(Integer... value) {
        setOperations_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecurityAccessPrivilege_Record value5(Integer... value) {
        setEntities_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecurityAccessPrivilege_Record value6(Integer... value) {
        setAttributes_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecurityAccessPrivilege_Record value7(Object value) {
        set_Search_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecurityAccessPrivilege_Record value8(String... value) {
        set_Types_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecurityAccessPrivilege_Record value9(String value) {
        set_LastModified_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecurityAccessPrivilege_Record value10(Integer value) {
        set_Version_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecurityAccessPrivilege_Record values(Integer value1, Integer value2, String value3, Integer[] value4, Integer[] value5, Integer[] value6, Object value7, String[] value8, String value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SecurityAccessPrivilege_Record
     */
    public SecurityAccessPrivilege_Record() {
        super(SecurityAccessPrivilege_.SECURITY_ACCESS_PRIVILEGE_);
    }

    /**
     * Create a detached, initialised SecurityAccessPrivilege_Record
     */
    public SecurityAccessPrivilege_Record(Integer _Id_, Integer _SecurityRoleId_, String name_, Integer[] operations_, Integer[] entities_, Integer[] attributes_, Object _Search_, String[] _Types_, String _LastModified_, Integer _Version_) {
        super(SecurityAccessPrivilege_.SECURITY_ACCESS_PRIVILEGE_);

        set(0, _Id_);
        set(1, _SecurityRoleId_);
        set(2, name_);
        set(3, operations_);
        set(4, entities_);
        set(5, attributes_);
        set(6, _Search_);
        set(7, _Types_);
        set(8, _LastModified_);
        set(9, _Version_);
    }
}
