/*
 * This file is generated by jOOQ.
*/
package es.eci.catalog.model.tables.records;


import es.eci.catalog.model.tables.SecurityOperationType_;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SecurityOperationType_Record extends UpdatableRecordImpl<SecurityOperationType_Record> implements Record6<Integer, String, Object, String[], String, Integer> {

    private static final long serialVersionUID = -583773601;

    /**
     * Setter for <code>public.security_operation_type_._id_</code>.
     */
    public void set_Id_(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.security_operation_type_._id_</code>.
     */
    public Integer get_Id_() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.security_operation_type_.name_</code>.
     */
    public void setName_(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.security_operation_type_.name_</code>.
     */
    public String getName_() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.security_operation_type_._search_</code>.
     */
    public void set_Search_(Object value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.security_operation_type_._search_</code>.
     */
    public Object get_Search_() {
        return (Object) get(2);
    }

    /**
     * Setter for <code>public.security_operation_type_._types_</code>.
     */
    public void set_Types_(String... value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.security_operation_type_._types_</code>.
     */
    public String[] get_Types_() {
        return (String[]) get(3);
    }

    /**
     * Setter for <code>public.security_operation_type_._last_modified_</code>.
     */
    public void set_LastModified_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.security_operation_type_._last_modified_</code>.
     */
    public String get_LastModified_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.security_operation_type_._version_</code>.
     */
    public void set_Version_(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.security_operation_type_._version_</code>.
     */
    public Integer get_Version_() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Object, String[], String, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Object, String[], String, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SecurityOperationType_.SECURITY_OPERATION_TYPE_._ID_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SecurityOperationType_.SECURITY_OPERATION_TYPE_.NAME_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field3() {
        return SecurityOperationType_.SECURITY_OPERATION_TYPE_._SEARCH_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field4() {
        return SecurityOperationType_.SECURITY_OPERATION_TYPE_._TYPES_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SecurityOperationType_.SECURITY_OPERATION_TYPE_._LAST_MODIFIED_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return SecurityOperationType_.SECURITY_OPERATION_TYPE_._VERSION_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return get_Id_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value3() {
        return get_Search_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value4() {
        return get_Types_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return get_LastModified_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return get_Version_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecurityOperationType_Record value1(Integer value) {
        set_Id_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecurityOperationType_Record value2(String value) {
        setName_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecurityOperationType_Record value3(Object value) {
        set_Search_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecurityOperationType_Record value4(String... value) {
        set_Types_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecurityOperationType_Record value5(String value) {
        set_LastModified_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecurityOperationType_Record value6(Integer value) {
        set_Version_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecurityOperationType_Record values(Integer value1, String value2, Object value3, String[] value4, String value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SecurityOperationType_Record
     */
    public SecurityOperationType_Record() {
        super(SecurityOperationType_.SECURITY_OPERATION_TYPE_);
    }

    /**
     * Create a detached, initialised SecurityOperationType_Record
     */
    public SecurityOperationType_Record(Integer _Id_, String name_, Object _Search_, String[] _Types_, String _LastModified_, Integer _Version_) {
        super(SecurityOperationType_.SECURITY_OPERATION_TYPE_);

        set(0, _Id_);
        set(1, name_);
        set(2, _Search_);
        set(3, _Types_);
        set(4, _LastModified_);
        set(5, _Version_);
    }
}
