/*
 * This file is generated by jOOQ.
*/
package es.eci.catalog.model.tables.records;


import es.eci.catalog.model.tables.TeachingCenter_;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record21;
import org.jooq.Row21;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeachingCenter_Record extends UpdatableRecordImpl<TeachingCenter_Record> implements Record21<Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, String, Double, Double, Object, String[], String, Integer> {

    private static final long serialVersionUID = 807437108;

    /**
     * Setter for <code>public.teaching_center_._id_</code>.
     */
    public void set_Id_(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.teaching_center_._id_</code>.
     */
    public Integer get_Id_() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.teaching_center_.name_</code>.
     */
    public void setName_(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.teaching_center_.name_</code>.
     */
    public String getName_() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.teaching_center_.generic_name_</code>.
     */
    public void setGenericName_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.teaching_center_.generic_name_</code>.
     */
    public String getGenericName_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.teaching_center_.email_</code>.
     */
    public void setEmail_(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.teaching_center_.email_</code>.
     */
    public String getEmail_() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.teaching_center_.phone_</code>.
     */
    public void setPhone_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.teaching_center_.phone_</code>.
     */
    public String getPhone_() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.teaching_center_.image_</code>.
     */
    public void setImage_(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.teaching_center_.image_</code>.
     */
    public String getImage_() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.teaching_center_.code_</code>.
     */
    public void setCode_(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.teaching_center_.code_</code>.
     */
    public String getCode_() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.teaching_center_.type_</code>.
     */
    public void setType_(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.teaching_center_.type_</code>.
     */
    public String getType_() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.teaching_center_.nature_</code>.
     */
    public void setNature_(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.teaching_center_.nature_</code>.
     */
    public String getNature_() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.teaching_center_.address_</code>.
     */
    public void setAddress_(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.teaching_center_.address_</code>.
     */
    public String getAddress_() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.teaching_center_.formatted_address_</code>.
     */
    public void setFormattedAddress_(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.teaching_center_.formatted_address_</code>.
     */
    public String getFormattedAddress_() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.teaching_center_.postal_code_</code>.
     */
    public void setPostalCode_(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.teaching_center_.postal_code_</code>.
     */
    public String getPostalCode_() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.teaching_center_.town_</code>.
     */
    public void setTown_(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.teaching_center_.town_</code>.
     */
    public String getTown_() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.teaching_center_.province_</code>.
     */
    public void setProvince_(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.teaching_center_.province_</code>.
     */
    public String getProvince_() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.teaching_center_.autonomous_region_</code>.
     */
    public void setAutonomousRegion_(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.teaching_center_.autonomous_region_</code>.
     */
    public String getAutonomousRegion_() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.teaching_center_.latitude_</code>.
     */
    public void setLatitude_(Double value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.teaching_center_.latitude_</code>.
     */
    public Double getLatitude_() {
        return (Double) get(15);
    }

    /**
     * Setter for <code>public.teaching_center_.longitude_</code>.
     */
    public void setLongitude_(Double value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.teaching_center_.longitude_</code>.
     */
    public Double getLongitude_() {
        return (Double) get(16);
    }

    /**
     * Setter for <code>public.teaching_center_._search_</code>.
     */
    public void set_Search_(Object value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.teaching_center_._search_</code>.
     */
    public Object get_Search_() {
        return (Object) get(17);
    }

    /**
     * Setter for <code>public.teaching_center_._types_</code>.
     */
    public void set_Types_(String... value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.teaching_center_._types_</code>.
     */
    public String[] get_Types_() {
        return (String[]) get(18);
    }

    /**
     * Setter for <code>public.teaching_center_._last_modified_</code>.
     */
    public void set_LastModified_(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.teaching_center_._last_modified_</code>.
     */
    public String get_LastModified_() {
        return (String) get(19);
    }

    /**
     * Setter for <code>public.teaching_center_._version_</code>.
     */
    public void set_Version_(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.teaching_center_._version_</code>.
     */
    public Integer get_Version_() {
        return (Integer) get(20);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record21 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row21<Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, String, Double, Double, Object, String[], String, Integer> fieldsRow() {
        return (Row21) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row21<Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, String, Double, Double, Object, String[], String, Integer> valuesRow() {
        return (Row21) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TeachingCenter_.TEACHING_CENTER_._ID_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TeachingCenter_.TEACHING_CENTER_.NAME_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TeachingCenter_.TEACHING_CENTER_.GENERIC_NAME_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TeachingCenter_.TEACHING_CENTER_.EMAIL_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TeachingCenter_.TEACHING_CENTER_.PHONE_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TeachingCenter_.TEACHING_CENTER_.IMAGE_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TeachingCenter_.TEACHING_CENTER_.CODE_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TeachingCenter_.TEACHING_CENTER_.TYPE_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TeachingCenter_.TEACHING_CENTER_.NATURE_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return TeachingCenter_.TEACHING_CENTER_.ADDRESS_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return TeachingCenter_.TEACHING_CENTER_.FORMATTED_ADDRESS_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return TeachingCenter_.TEACHING_CENTER_.POSTAL_CODE_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return TeachingCenter_.TEACHING_CENTER_.TOWN_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return TeachingCenter_.TEACHING_CENTER_.PROVINCE_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return TeachingCenter_.TEACHING_CENTER_.AUTONOMOUS_REGION_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field16() {
        return TeachingCenter_.TEACHING_CENTER_.LATITUDE_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field17() {
        return TeachingCenter_.TEACHING_CENTER_.LONGITUDE_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field18() {
        return TeachingCenter_.TEACHING_CENTER_._SEARCH_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field19() {
        return TeachingCenter_.TEACHING_CENTER_._TYPES_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field20() {
        return TeachingCenter_.TEACHING_CENTER_._LAST_MODIFIED_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field21() {
        return TeachingCenter_.TEACHING_CENTER_._VERSION_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return get_Id_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getGenericName_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEmail_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPhone_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getImage_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCode_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getType_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getNature_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getAddress_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getFormattedAddress_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getPostalCode_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getTown_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getProvince_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getAutonomousRegion_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value16() {
        return getLatitude_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value17() {
        return getLongitude_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value18() {
        return get_Search_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value19() {
        return get_Types_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value20() {
        return get_LastModified_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value21() {
        return get_Version_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeachingCenter_Record value1(Integer value) {
        set_Id_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeachingCenter_Record value2(String value) {
        setName_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeachingCenter_Record value3(String value) {
        setGenericName_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeachingCenter_Record value4(String value) {
        setEmail_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeachingCenter_Record value5(String value) {
        setPhone_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeachingCenter_Record value6(String value) {
        setImage_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeachingCenter_Record value7(String value) {
        setCode_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeachingCenter_Record value8(String value) {
        setType_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeachingCenter_Record value9(String value) {
        setNature_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeachingCenter_Record value10(String value) {
        setAddress_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeachingCenter_Record value11(String value) {
        setFormattedAddress_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeachingCenter_Record value12(String value) {
        setPostalCode_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeachingCenter_Record value13(String value) {
        setTown_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeachingCenter_Record value14(String value) {
        setProvince_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeachingCenter_Record value15(String value) {
        setAutonomousRegion_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeachingCenter_Record value16(Double value) {
        setLatitude_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeachingCenter_Record value17(Double value) {
        setLongitude_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeachingCenter_Record value18(Object value) {
        set_Search_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeachingCenter_Record value19(String... value) {
        set_Types_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeachingCenter_Record value20(String value) {
        set_LastModified_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeachingCenter_Record value21(Integer value) {
        set_Version_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TeachingCenter_Record values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, Double value16, Double value17, Object value18, String[] value19, String value20, Integer value21) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeachingCenter_Record
     */
    public TeachingCenter_Record() {
        super(TeachingCenter_.TEACHING_CENTER_);
    }

    /**
     * Create a detached, initialised TeachingCenter_Record
     */
    public TeachingCenter_Record(Integer _Id_, String name_, String genericName_, String email_, String phone_, String image_, String code_, String type_, String nature_, String address_, String formattedAddress_, String postalCode_, String town_, String province_, String autonomousRegion_, Double latitude_, Double longitude_, Object _Search_, String[] _Types_, String _LastModified_, Integer _Version_) {
        super(TeachingCenter_.TEACHING_CENTER_);

        set(0, _Id_);
        set(1, name_);
        set(2, genericName_);
        set(3, email_);
        set(4, phone_);
        set(5, image_);
        set(6, code_);
        set(7, type_);
        set(8, nature_);
        set(9, address_);
        set(10, formattedAddress_);
        set(11, postalCode_);
        set(12, town_);
        set(13, province_);
        set(14, autonomousRegion_);
        set(15, latitude_);
        set(16, longitude_);
        set(17, _Search_);
        set(18, _Types_);
        set(19, _LastModified_);
        set(20, _Version_);
    }
}
