/*
 * This file is generated by jOOQ.
*/
package es.eci.catalog.model.udt.records;


import es.eci.catalog.model.udt.Person_;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UDTRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Person_Record extends UDTRecordImpl<Person_Record> implements Record5<String, String, String, String[], String> {

    private static final long serialVersionUID = 1960923503;

    /**
     * Setter for <code>public.person_.email_</code>.
     */
    public void setEmail_(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.person_.email_</code>.
     */
    public String getEmail_() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.person_.birth_date_</code>.
     */
    public void setBirthDate_(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.person_.birth_date_</code>.
     */
    public String getBirthDate_() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.person_.photo_</code>.
     */
    public void setPhoto_(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.person_.photo_</code>.
     */
    public String getPhoto_() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.person_.identity_cards_</code>.
     */
    public void setIdentityCards_(String... value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.person_.identity_cards_</code>.
     */
    public String[] getIdentityCards_() {
        return (String[]) get(3);
    }

    /**
     * Setter for <code>public.person_.presentation_video_</code>.
     */
    public void setPresentationVideo_(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.person_.presentation_video_</code>.
     */
    public String getPresentationVideo_() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, String[], String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, String[], String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Person_.EMAIL_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Person_.BIRTH_DATE_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Person_.PHOTO_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field4() {
        return Person_.IDENTITY_CARDS_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Person_.PRESENTATION_VIDEO_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getEmail_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBirthDate_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPhoto_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value4() {
        return getIdentityCards_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPresentationVideo_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Person_Record value1(String value) {
        setEmail_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Person_Record value2(String value) {
        setBirthDate_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Person_Record value3(String value) {
        setPhoto_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Person_Record value4(String... value) {
        setIdentityCards_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Person_Record value5(String value) {
        setPresentationVideo_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Person_Record values(String value1, String value2, String value3, String[] value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Person_Record
     */
    public Person_Record() {
        super(Person_.PERSON_);
    }

    /**
     * Create a detached, initialised Person_Record
     */
    public Person_Record(String email_, String birthDate_, String photo_, String[] identityCards_, String presentationVideo_) {
        super(Person_.PERSON_);

        set(0, email_);
        set(1, birthDate_);
        set(2, photo_);
        set(3, identityCards_);
        set(4, presentationVideo_);
    }
}
