/*
 * This file is generated by jOOQ.
*/
package es.eci.catalog.model.udt;


import es.eci.catalog.model.Public;
import es.eci.catalog.model.udt.records.Person_Record;

import javax.annotation.Generated;

import org.jooq.Schema;
import org.jooq.UDTField;
import org.jooq.impl.UDTImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Person_ extends UDTImpl<Person_Record> {

    private static final long serialVersionUID = -1797656025;

    /**
     * The reference instance of <code>public.person_</code>
     */
    public static final Person_ PERSON_ = new Person_();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Person_Record> getRecordType() {
        return Person_Record.class;
    }

    /**
     * The attribute <code>public.person_.email_</code>.
     */
    public static final UDTField<Person_Record, String> EMAIL_ = createField("email_", org.jooq.impl.SQLDataType.VARCHAR, PERSON_, "");

    /**
     * The attribute <code>public.person_.birth_date_</code>.
     */
    public static final UDTField<Person_Record, String> BIRTH_DATE_ = createField("birth_date_", org.jooq.impl.SQLDataType.VARCHAR, PERSON_, "");

    /**
     * The attribute <code>public.person_.photo_</code>.
     */
    public static final UDTField<Person_Record, String> PHOTO_ = createField("photo_", org.jooq.impl.SQLDataType.VARCHAR, PERSON_, "");

    /**
     * The attribute <code>public.person_.identity_cards_</code>.
     */
    public static final UDTField<Person_Record, String[]> IDENTITY_CARDS_ = createField("identity_cards_", org.jooq.impl.SQLDataType.VARCHAR.getArrayDataType(), PERSON_, "");

    /**
     * The attribute <code>public.person_.presentation_video_</code>.
     */
    public static final UDTField<Person_Record, String> PRESENTATION_VIDEO_ = createField("presentation_video_", org.jooq.impl.SQLDataType.VARCHAR, PERSON_, "");

    /**
     * No further instances allowed
     */
    private Person_() {
        super("person_", null);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }
}
