/*
 * This file is generated by jOOQ.
*/
package es.eci.catalog.model.tables;


import es.eci.catalog.model.Keys;
import es.eci.catalog.model.Public;
import es.eci.catalog.model.tables.records.Material_Record;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Material_ extends TableImpl<Material_Record> {

    private static final long serialVersionUID = -699632663;

    /**
     * The reference instance of <code>public.material_</code>
     */
    public static final Material_ MATERIAL_ = new Material_();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Material_Record> getRecordType() {
        return Material_Record.class;
    }

    /**
     * The column <code>public.material_._id_</code>.
     */
    public final TableField<Material_Record, Integer> _ID_ = createField("_id_", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('material___id__seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.material_._course_id_</code>.
     */
    public final TableField<Material_Record, Integer> _COURSE_ID_ = createField("_course_id_", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.material_.quantity_</code>.
     */
    public final TableField<Material_Record, Integer> QUANTITY_ = createField("quantity_", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.material_.item_</code>.
     */
    public final TableField<Material_Record, Integer> ITEM_ = createField("item_", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.material_._search_</code>.
     */
    public final TableField<Material_Record, Object> _SEARCH_ = createField("_search_", org.jooq.impl.DefaultDataType.getDefaultDataType("tsvector"), this, "");

    /**
     * The column <code>public.material_._types_</code>.
     */
    public final TableField<Material_Record, String[]> _TYPES_ = createField("_types_", org.jooq.impl.SQLDataType.VARCHAR.getArrayDataType(), this, "");

    /**
     * The column <code>public.material_._last_modified_</code>.
     */
    public final TableField<Material_Record, String> _LAST_MODIFIED_ = createField("_last_modified_", org.jooq.impl.SQLDataType.VARCHAR.defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.material_._version_</code>.
     */
    public final TableField<Material_Record, Integer> _VERSION_ = createField("_version_", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>public.material_</code> table reference
     */
    public Material_() {
        this("material_", null);
    }

    /**
     * Create an aliased <code>public.material_</code> table reference
     */
    public Material_(String alias) {
        this(alias, MATERIAL_);
    }

    private Material_(String alias, Table<Material_Record> aliased) {
        this(alias, aliased, null);
    }

    private Material_(String alias, Table<Material_Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<Material_Record, Integer> getIdentity() {
        return Keys.IDENTITY_MATERIAL_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Material_Record> getPrimaryKey() {
        return Keys.MATERIAL__PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Material_Record>> getKeys() {
        return Arrays.<UniqueKey<Material_Record>>asList(Keys.MATERIAL__PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<Material_Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Material_Record, ?>>asList(Keys.MATERIAL___MATERIAL_MASTER_, Keys.MATERIAL___MATERIAL_ITEM_);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TableField<Material_Record, Integer> getRecordVersion() {
        return _VERSION_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Material_ as(String alias) {
        return new Material_(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Material_ rename(String name) {
        return new Material_(name, null);
    }
}
