/*
 * This file is generated by jOOQ.
*/
package es.eci.catalog.model.tables;


import es.eci.catalog.model.Keys;
import es.eci.catalog.model.Public;
import es.eci.catalog.model.tables.records.SecurityRowLevelPolicy_Record;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SecurityRowLevelPolicy_ extends TableImpl<SecurityRowLevelPolicy_Record> {

    private static final long serialVersionUID = 1660976068;

    /**
     * The reference instance of <code>public.security_row_level_policy_</code>
     */
    public static final SecurityRowLevelPolicy_ SECURITY_ROW_LEVEL_POLICY_ = new SecurityRowLevelPolicy_();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SecurityRowLevelPolicy_Record> getRecordType() {
        return SecurityRowLevelPolicy_Record.class;
    }

    /**
     * The column <code>public.security_row_level_policy_._id_</code>.
     */
    public final TableField<SecurityRowLevelPolicy_Record, Integer> _ID_ = createField("_id_", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('security_row_level_policy___id__seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.security_row_level_policy_._security_role_id_</code>.
     */
    public final TableField<SecurityRowLevelPolicy_Record, Integer> _SECURITY_ROLE_ID_ = createField("_security_role_id_", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.security_row_level_policy_.name_</code>.
     */
    public final TableField<SecurityRowLevelPolicy_Record, String> NAME_ = createField("name_", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.security_row_level_policy_.entity_</code>.
     */
    public final TableField<SecurityRowLevelPolicy_Record, Integer> ENTITY_ = createField("entity_", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.security_row_level_policy_.operations_</code>.
     */
    public final TableField<SecurityRowLevelPolicy_Record, Integer[]> OPERATIONS_ = createField("operations_", org.jooq.impl.SQLDataType.INTEGER.getArrayDataType(), this, "");

    /**
     * The column <code>public.security_row_level_policy_.using_expression_</code>.
     */
    public final TableField<SecurityRowLevelPolicy_Record, String> USING_EXPRESSION_ = createField("using_expression_", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.security_row_level_policy_.check_expression_</code>.
     */
    public final TableField<SecurityRowLevelPolicy_Record, String> CHECK_EXPRESSION_ = createField("check_expression_", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.security_row_level_policy_._search_</code>.
     */
    public final TableField<SecurityRowLevelPolicy_Record, Object> _SEARCH_ = createField("_search_", org.jooq.impl.DefaultDataType.getDefaultDataType("tsvector"), this, "");

    /**
     * The column <code>public.security_row_level_policy_._types_</code>.
     */
    public final TableField<SecurityRowLevelPolicy_Record, String[]> _TYPES_ = createField("_types_", org.jooq.impl.SQLDataType.VARCHAR.getArrayDataType(), this, "");

    /**
     * The column <code>public.security_row_level_policy_._last_modified_</code>.
     */
    public final TableField<SecurityRowLevelPolicy_Record, String> _LAST_MODIFIED_ = createField("_last_modified_", org.jooq.impl.SQLDataType.VARCHAR.defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.security_row_level_policy_._version_</code>.
     */
    public final TableField<SecurityRowLevelPolicy_Record, Integer> _VERSION_ = createField("_version_", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>public.security_row_level_policy_</code> table reference
     */
    public SecurityRowLevelPolicy_() {
        this("security_row_level_policy_", null);
    }

    /**
     * Create an aliased <code>public.security_row_level_policy_</code> table reference
     */
    public SecurityRowLevelPolicy_(String alias) {
        this(alias, SECURITY_ROW_LEVEL_POLICY_);
    }

    private SecurityRowLevelPolicy_(String alias, Table<SecurityRowLevelPolicy_Record> aliased) {
        this(alias, aliased, null);
    }

    private SecurityRowLevelPolicy_(String alias, Table<SecurityRowLevelPolicy_Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SecurityRowLevelPolicy_Record, Integer> getIdentity() {
        return Keys.IDENTITY_SECURITY_ROW_LEVEL_POLICY_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SecurityRowLevelPolicy_Record> getPrimaryKey() {
        return Keys.SECURITY_ROW_LEVEL_POLICY__PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SecurityRowLevelPolicy_Record>> getKeys() {
        return Arrays.<UniqueKey<SecurityRowLevelPolicy_Record>>asList(Keys.SECURITY_ROW_LEVEL_POLICY__PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<SecurityRowLevelPolicy_Record, ?>> getReferences() {
        return Arrays.<ForeignKey<SecurityRowLevelPolicy_Record, ?>>asList(Keys.SECURITY_ROW_LEVEL_POLICY___SECURITY_ROW_LEVEL_POLICY_MASTER_, Keys.SECURITY_ROW_LEVEL_POLICY___SECURITY_ROW_LEVEL_POLICY_ENTITY_);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TableField<SecurityRowLevelPolicy_Record, Integer> getRecordVersion() {
        return _VERSION_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecurityRowLevelPolicy_ as(String alias) {
        return new SecurityRowLevelPolicy_(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SecurityRowLevelPolicy_ rename(String name) {
        return new SecurityRowLevelPolicy_(name, null);
    }
}
