/*
 * This file is generated by jOOQ.
*/
package es.eci.catalog.model.tables;


import es.eci.catalog.model.Keys;
import es.eci.catalog.model.Public;
import es.eci.catalog.model.tables.records.SecurityAccessPrivilege_Record;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SecurityAccessPrivilege_ extends TableImpl<SecurityAccessPrivilege_Record> {

    private static final long serialVersionUID = 1079805044;

    /**
     * The reference instance of <code>public.security_access_privilege_</code>
     */
    public static final SecurityAccessPrivilege_ SECURITY_ACCESS_PRIVILEGE_ = new SecurityAccessPrivilege_();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SecurityAccessPrivilege_Record> getRecordType() {
        return SecurityAccessPrivilege_Record.class;
    }

    /**
     * The column <code>public.security_access_privilege_._id_</code>.
     */
    public final TableField<SecurityAccessPrivilege_Record, Integer> _ID_ = createField("_id_", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('security_access_privilege___id__seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.security_access_privilege_._security_role_id_</code>.
     */
    public final TableField<SecurityAccessPrivilege_Record, Integer> _SECURITY_ROLE_ID_ = createField("_security_role_id_", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.security_access_privilege_.name_</code>.
     */
    public final TableField<SecurityAccessPrivilege_Record, String> NAME_ = createField("name_", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.security_access_privilege_.operations_</code>.
     */
    public final TableField<SecurityAccessPrivilege_Record, Integer[]> OPERATIONS_ = createField("operations_", org.jooq.impl.SQLDataType.INTEGER.getArrayDataType(), this, "");

    /**
     * The column <code>public.security_access_privilege_.entities_</code>.
     */
    public final TableField<SecurityAccessPrivilege_Record, Integer[]> ENTITIES_ = createField("entities_", org.jooq.impl.SQLDataType.INTEGER.getArrayDataType(), this, "");

    /**
     * The column <code>public.security_access_privilege_.attributes_</code>.
     */
    public final TableField<SecurityAccessPrivilege_Record, Integer[]> ATTRIBUTES_ = createField("attributes_", org.jooq.impl.SQLDataType.INTEGER.getArrayDataType(), this, "");

    /**
     * The column <code>public.security_access_privilege_._search_</code>.
     */
    public final TableField<SecurityAccessPrivilege_Record, Object> _SEARCH_ = createField("_search_", org.jooq.impl.DefaultDataType.getDefaultDataType("tsvector"), this, "");

    /**
     * The column <code>public.security_access_privilege_._types_</code>.
     */
    public final TableField<SecurityAccessPrivilege_Record, String[]> _TYPES_ = createField("_types_", org.jooq.impl.SQLDataType.VARCHAR.getArrayDataType(), this, "");

    /**
     * The column <code>public.security_access_privilege_._last_modified_</code>.
     */
    public final TableField<SecurityAccessPrivilege_Record, String> _LAST_MODIFIED_ = createField("_last_modified_", org.jooq.impl.SQLDataType.VARCHAR.defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.security_access_privilege_._version_</code>.
     */
    public final TableField<SecurityAccessPrivilege_Record, Integer> _VERSION_ = createField("_version_", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>public.security_access_privilege_</code> table reference
     */
    public SecurityAccessPrivilege_() {
        this("security_access_privilege_", null);
    }

    /**
     * Create an aliased <code>public.security_access_privilege_</code> table reference
     */
    public SecurityAccessPrivilege_(String alias) {
        this(alias, SECURITY_ACCESS_PRIVILEGE_);
    }

    private SecurityAccessPrivilege_(String alias, Table<SecurityAccessPrivilege_Record> aliased) {
        this(alias, aliased, null);
    }

    private SecurityAccessPrivilege_(String alias, Table<SecurityAccessPrivilege_Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SecurityAccessPrivilege_Record, Integer> getIdentity() {
        return Keys.IDENTITY_SECURITY_ACCESS_PRIVILEGE_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SecurityAccessPrivilege_Record> getPrimaryKey() {
        return Keys.SECURITY_ACCESS_PRIVILEGE__PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SecurityAccessPrivilege_Record>> getKeys() {
        return Arrays.<UniqueKey<SecurityAccessPrivilege_Record>>asList(Keys.SECURITY_ACCESS_PRIVILEGE__PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<SecurityAccessPrivilege_Record, ?>> getReferences() {
        return Arrays.<ForeignKey<SecurityAccessPrivilege_Record, ?>>asList(Keys.SECURITY_ACCESS_PRIVILEGE___SECURITY_ACCESS_PRIVILEGE_MASTER_);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TableField<SecurityAccessPrivilege_Record, Integer> getRecordVersion() {
        return _VERSION_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecurityAccessPrivilege_ as(String alias) {
        return new SecurityAccessPrivilege_(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SecurityAccessPrivilege_ rename(String name) {
        return new SecurityAccessPrivilege_(name, null);
    }
}
