/*
 * This file is generated by jOOQ.
*/
package es.eci.catalog.model.tables;


import es.eci.catalog.model.Keys;
import es.eci.catalog.model.Public;
import es.eci.catalog.model.tables.records.SecurityOperationType_Record;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SecurityOperationType_ extends TableImpl<SecurityOperationType_Record> {

    private static final long serialVersionUID = -454971515;

    /**
     * The reference instance of <code>public.security_operation_type_</code>
     */
    public static final SecurityOperationType_ SECURITY_OPERATION_TYPE_ = new SecurityOperationType_();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SecurityOperationType_Record> getRecordType() {
        return SecurityOperationType_Record.class;
    }

    /**
     * The column <code>public.security_operation_type_._id_</code>.
     */
    public final TableField<SecurityOperationType_Record, Integer> _ID_ = createField("_id_", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('security_operation_type___id__seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.security_operation_type_.name_</code>.
     */
    public final TableField<SecurityOperationType_Record, String> NAME_ = createField("name_", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.security_operation_type_._search_</code>.
     */
    public final TableField<SecurityOperationType_Record, Object> _SEARCH_ = createField("_search_", org.jooq.impl.DefaultDataType.getDefaultDataType("tsvector"), this, "");

    /**
     * The column <code>public.security_operation_type_._types_</code>.
     */
    public final TableField<SecurityOperationType_Record, String[]> _TYPES_ = createField("_types_", org.jooq.impl.SQLDataType.VARCHAR.getArrayDataType(), this, "");

    /**
     * The column <code>public.security_operation_type_._last_modified_</code>.
     */
    public final TableField<SecurityOperationType_Record, String> _LAST_MODIFIED_ = createField("_last_modified_", org.jooq.impl.SQLDataType.VARCHAR.defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.security_operation_type_._version_</code>.
     */
    public final TableField<SecurityOperationType_Record, Integer> _VERSION_ = createField("_version_", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>public.security_operation_type_</code> table reference
     */
    public SecurityOperationType_() {
        this("security_operation_type_", null);
    }

    /**
     * Create an aliased <code>public.security_operation_type_</code> table reference
     */
    public SecurityOperationType_(String alias) {
        this(alias, SECURITY_OPERATION_TYPE_);
    }

    private SecurityOperationType_(String alias, Table<SecurityOperationType_Record> aliased) {
        this(alias, aliased, null);
    }

    private SecurityOperationType_(String alias, Table<SecurityOperationType_Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SecurityOperationType_Record, Integer> getIdentity() {
        return Keys.IDENTITY_SECURITY_OPERATION_TYPE_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SecurityOperationType_Record> getPrimaryKey() {
        return Keys.SECURITY_OPERATION_TYPE__PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SecurityOperationType_Record>> getKeys() {
        return Arrays.<UniqueKey<SecurityOperationType_Record>>asList(Keys.SECURITY_OPERATION_TYPE__PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TableField<SecurityOperationType_Record, Integer> getRecordVersion() {
        return _VERSION_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecurityOperationType_ as(String alias) {
        return new SecurityOperationType_(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SecurityOperationType_ rename(String name) {
        return new SecurityOperationType_(name, null);
    }
}
