/*
 * This file is generated by jOOQ.
*/
package es.eci.catalog.model.tables;


import es.eci.catalog.model.Keys;
import es.eci.catalog.model.Public;
import es.eci.catalog.model.tables.records.SecurityEntity_Record;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SecurityEntity_ extends TableImpl<SecurityEntity_Record> {

    private static final long serialVersionUID = 335942707;

    /**
     * The reference instance of <code>public.security_entity_</code>
     */
    public static final SecurityEntity_ SECURITY_ENTITY_ = new SecurityEntity_();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SecurityEntity_Record> getRecordType() {
        return SecurityEntity_Record.class;
    }

    /**
     * The column <code>public.security_entity_._id_</code>.
     */
    public final TableField<SecurityEntity_Record, Integer> _ID_ = createField("_id_", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('security_entity___id__seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.security_entity_.name_</code>.
     */
    public final TableField<SecurityEntity_Record, String> NAME_ = createField("name_", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.security_entity_._search_</code>.
     */
    public final TableField<SecurityEntity_Record, Object> _SEARCH_ = createField("_search_", org.jooq.impl.DefaultDataType.getDefaultDataType("tsvector"), this, "");

    /**
     * The column <code>public.security_entity_._types_</code>.
     */
    public final TableField<SecurityEntity_Record, String[]> _TYPES_ = createField("_types_", org.jooq.impl.SQLDataType.VARCHAR.getArrayDataType(), this, "");

    /**
     * The column <code>public.security_entity_._last_modified_</code>.
     */
    public final TableField<SecurityEntity_Record, String> _LAST_MODIFIED_ = createField("_last_modified_", org.jooq.impl.SQLDataType.VARCHAR.defaultValue(org.jooq.impl.DSL.field("now()", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.security_entity_._version_</code>.
     */
    public final TableField<SecurityEntity_Record, Integer> _VERSION_ = createField("_version_", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>public.security_entity_</code> table reference
     */
    public SecurityEntity_() {
        this("security_entity_", null);
    }

    /**
     * Create an aliased <code>public.security_entity_</code> table reference
     */
    public SecurityEntity_(String alias) {
        this(alias, SECURITY_ENTITY_);
    }

    private SecurityEntity_(String alias, Table<SecurityEntity_Record> aliased) {
        this(alias, aliased, null);
    }

    private SecurityEntity_(String alias, Table<SecurityEntity_Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SecurityEntity_Record, Integer> getIdentity() {
        return Keys.IDENTITY_SECURITY_ENTITY_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SecurityEntity_Record> getPrimaryKey() {
        return Keys.SECURITY_ENTITY__PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SecurityEntity_Record>> getKeys() {
        return Arrays.<UniqueKey<SecurityEntity_Record>>asList(Keys.SECURITY_ENTITY__PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TableField<SecurityEntity_Record, Integer> getRecordVersion() {
        return _VERSION_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecurityEntity_ as(String alias) {
        return new SecurityEntity_(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SecurityEntity_ rename(String name) {
        return new SecurityEntity_(name, null);
    }
}
