/*
 * This file is generated by jOOQ.
*/
package es.eci.catalog.model;


import es.eci.catalog.model.tables.Course_;
import es.eci.catalog.model.tables.ItemImage_;
import es.eci.catalog.model.tables.Item_;
import es.eci.catalog.model.tables.Material_;
import es.eci.catalog.model.tables.SchedulingProcess_;
import es.eci.catalog.model.tables.SecurityAccessPrivilege_;
import es.eci.catalog.model.tables.SecurityAttribute_;
import es.eci.catalog.model.tables.SecurityEntity_;
import es.eci.catalog.model.tables.SecurityOperationType_;
import es.eci.catalog.model.tables.SecurityRole_;
import es.eci.catalog.model.tables.SecurityRowLevelPolicy_;
import es.eci.catalog.model.tables.SecurityUser_;
import es.eci.catalog.model.tables.TeachingCenter_;
import es.eci.catalog.model.udt.Person_;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.UDT;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -343165829;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.course_</code>.
     */
    public final Course_ COURSE_ = es.eci.catalog.model.tables.Course_.COURSE_;

    /**
     * The table <code>public.item_</code>.
     */
    public final Item_ ITEM_ = es.eci.catalog.model.tables.Item_.ITEM_;

    /**
     * The table <code>public.item_image_</code>.
     */
    public final ItemImage_ ITEM_IMAGE_ = es.eci.catalog.model.tables.ItemImage_.ITEM_IMAGE_;

    /**
     * The table <code>public.material_</code>.
     */
    public final Material_ MATERIAL_ = es.eci.catalog.model.tables.Material_.MATERIAL_;

    /**
     * The table <code>public.scheduling_process_</code>.
     */
    public final SchedulingProcess_ SCHEDULING_PROCESS_ = es.eci.catalog.model.tables.SchedulingProcess_.SCHEDULING_PROCESS_;

    /**
     * The table <code>public.security_access_privilege_</code>.
     */
    public final SecurityAccessPrivilege_ SECURITY_ACCESS_PRIVILEGE_ = es.eci.catalog.model.tables.SecurityAccessPrivilege_.SECURITY_ACCESS_PRIVILEGE_;

    /**
     * The table <code>public.security_attribute_</code>.
     */
    public final SecurityAttribute_ SECURITY_ATTRIBUTE_ = es.eci.catalog.model.tables.SecurityAttribute_.SECURITY_ATTRIBUTE_;

    /**
     * The table <code>public.security_entity_</code>.
     */
    public final SecurityEntity_ SECURITY_ENTITY_ = es.eci.catalog.model.tables.SecurityEntity_.SECURITY_ENTITY_;

    /**
     * The table <code>public.security_operation_type_</code>.
     */
    public final SecurityOperationType_ SECURITY_OPERATION_TYPE_ = es.eci.catalog.model.tables.SecurityOperationType_.SECURITY_OPERATION_TYPE_;

    /**
     * The table <code>public.security_role_</code>.
     */
    public final SecurityRole_ SECURITY_ROLE_ = es.eci.catalog.model.tables.SecurityRole_.SECURITY_ROLE_;

    /**
     * The table <code>public.security_row_level_policy_</code>.
     */
    public final SecurityRowLevelPolicy_ SECURITY_ROW_LEVEL_POLICY_ = es.eci.catalog.model.tables.SecurityRowLevelPolicy_.SECURITY_ROW_LEVEL_POLICY_;

    /**
     * The table <code>public.security_user_</code>.
     */
    public final SecurityUser_ SECURITY_USER_ = es.eci.catalog.model.tables.SecurityUser_.SECURITY_USER_;

    /**
     * The table <code>public.teaching_center_</code>.
     */
    public final TeachingCenter_ TEACHING_CENTER_ = es.eci.catalog.model.tables.TeachingCenter_.TEACHING_CENTER_;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.COURSE___ID__SEQ,
            Sequences.ITEM___ID__SEQ,
            Sequences.ITEM_IMAGE___ID__SEQ,
            Sequences.MATERIAL___ID__SEQ,
            Sequences.SCHEDULING_PROCESS___ID__SEQ,
            Sequences.SECURITY_ACCESS_PRIVILEGE___ID__SEQ,
            Sequences.SECURITY_ATTRIBUTE___ID__SEQ,
            Sequences.SECURITY_ENTITY___ID__SEQ,
            Sequences.SECURITY_OPERATION_TYPE___ID__SEQ,
            Sequences.SECURITY_ROLE___ID__SEQ,
            Sequences.SECURITY_ROW_LEVEL_POLICY___ID__SEQ,
            Sequences.SECURITY_USER___ID__SEQ,
            Sequences.TEACHING_CENTER___ID__SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Course_.COURSE_,
            Item_.ITEM_,
            ItemImage_.ITEM_IMAGE_,
            Material_.MATERIAL_,
            SchedulingProcess_.SCHEDULING_PROCESS_,
            SecurityAccessPrivilege_.SECURITY_ACCESS_PRIVILEGE_,
            SecurityAttribute_.SECURITY_ATTRIBUTE_,
            SecurityEntity_.SECURITY_ENTITY_,
            SecurityOperationType_.SECURITY_OPERATION_TYPE_,
            SecurityRole_.SECURITY_ROLE_,
            SecurityRowLevelPolicy_.SECURITY_ROW_LEVEL_POLICY_,
            SecurityUser_.SECURITY_USER_,
            TeachingCenter_.TEACHING_CENTER_);
    }

    @Override
    public final List<UDT<?>> getUDTs() {
        List result = new ArrayList();
        result.addAll(getUDTs0());
        return result;
    }

    private final List<UDT<?>> getUDTs0() {
        return Arrays.<UDT<?>>asList(
            Person_.PERSON_);
    }
}
