/*
 * This file is generated by jOOQ.
*/
package es.eci.catalog.model;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.course___id__seq</code>
     */
    public static final Sequence<Long> COURSE___ID__SEQ = new SequenceImpl<Long>("course___id__seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.item___id__seq</code>
     */
    public static final Sequence<Long> ITEM___ID__SEQ = new SequenceImpl<Long>("item___id__seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.item_image___id__seq</code>
     */
    public static final Sequence<Long> ITEM_IMAGE___ID__SEQ = new SequenceImpl<Long>("item_image___id__seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.material___id__seq</code>
     */
    public static final Sequence<Long> MATERIAL___ID__SEQ = new SequenceImpl<Long>("material___id__seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.scheduling_process___id__seq</code>
     */
    public static final Sequence<Long> SCHEDULING_PROCESS___ID__SEQ = new SequenceImpl<Long>("scheduling_process___id__seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.security_access_privilege___id__seq</code>
     */
    public static final Sequence<Long> SECURITY_ACCESS_PRIVILEGE___ID__SEQ = new SequenceImpl<Long>("security_access_privilege___id__seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.security_attribute___id__seq</code>
     */
    public static final Sequence<Long> SECURITY_ATTRIBUTE___ID__SEQ = new SequenceImpl<Long>("security_attribute___id__seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.security_entity___id__seq</code>
     */
    public static final Sequence<Long> SECURITY_ENTITY___ID__SEQ = new SequenceImpl<Long>("security_entity___id__seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.security_operation_type___id__seq</code>
     */
    public static final Sequence<Long> SECURITY_OPERATION_TYPE___ID__SEQ = new SequenceImpl<Long>("security_operation_type___id__seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.security_role___id__seq</code>
     */
    public static final Sequence<Long> SECURITY_ROLE___ID__SEQ = new SequenceImpl<Long>("security_role___id__seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.security_row_level_policy___id__seq</code>
     */
    public static final Sequence<Long> SECURITY_ROW_LEVEL_POLICY___ID__SEQ = new SequenceImpl<Long>("security_row_level_policy___id__seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.security_user___id__seq</code>
     */
    public static final Sequence<Long> SECURITY_USER___ID__SEQ = new SequenceImpl<Long>("security_user___id__seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.teaching_center___id__seq</code>
     */
    public static final Sequence<Long> TEACHING_CENTER___ID__SEQ = new SequenceImpl<Long>("teaching_center___id__seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
