/*
 * This file is generated by jOOQ.
*/
package es.eci.catalog.model;


import es.eci.catalog.model.tables.Course_;
import es.eci.catalog.model.tables.ItemImage_;
import es.eci.catalog.model.tables.Item_;
import es.eci.catalog.model.tables.Material_;
import es.eci.catalog.model.tables.SchedulingProcess_;
import es.eci.catalog.model.tables.SecurityAccessPrivilege_;
import es.eci.catalog.model.tables.SecurityAttribute_;
import es.eci.catalog.model.tables.SecurityEntity_;
import es.eci.catalog.model.tables.SecurityOperationType_;
import es.eci.catalog.model.tables.SecurityRole_;
import es.eci.catalog.model.tables.SecurityRowLevelPolicy_;
import es.eci.catalog.model.tables.SecurityUser_;
import es.eci.catalog.model.tables.TeachingCenter_;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.course_</code>.
     */
    public static final Course_ COURSE_ = es.eci.catalog.model.tables.Course_.COURSE_;

    /**
     * The table <code>public.item_</code>.
     */
    public static final Item_ ITEM_ = es.eci.catalog.model.tables.Item_.ITEM_;

    /**
     * The table <code>public.item_image_</code>.
     */
    public static final ItemImage_ ITEM_IMAGE_ = es.eci.catalog.model.tables.ItemImage_.ITEM_IMAGE_;

    /**
     * The table <code>public.material_</code>.
     */
    public static final Material_ MATERIAL_ = es.eci.catalog.model.tables.Material_.MATERIAL_;

    /**
     * The table <code>public.scheduling_process_</code>.
     */
    public static final SchedulingProcess_ SCHEDULING_PROCESS_ = es.eci.catalog.model.tables.SchedulingProcess_.SCHEDULING_PROCESS_;

    /**
     * The table <code>public.security_access_privilege_</code>.
     */
    public static final SecurityAccessPrivilege_ SECURITY_ACCESS_PRIVILEGE_ = es.eci.catalog.model.tables.SecurityAccessPrivilege_.SECURITY_ACCESS_PRIVILEGE_;

    /**
     * The table <code>public.security_attribute_</code>.
     */
    public static final SecurityAttribute_ SECURITY_ATTRIBUTE_ = es.eci.catalog.model.tables.SecurityAttribute_.SECURITY_ATTRIBUTE_;

    /**
     * The table <code>public.security_entity_</code>.
     */
    public static final SecurityEntity_ SECURITY_ENTITY_ = es.eci.catalog.model.tables.SecurityEntity_.SECURITY_ENTITY_;

    /**
     * The table <code>public.security_operation_type_</code>.
     */
    public static final SecurityOperationType_ SECURITY_OPERATION_TYPE_ = es.eci.catalog.model.tables.SecurityOperationType_.SECURITY_OPERATION_TYPE_;

    /**
     * The table <code>public.security_role_</code>.
     */
    public static final SecurityRole_ SECURITY_ROLE_ = es.eci.catalog.model.tables.SecurityRole_.SECURITY_ROLE_;

    /**
     * The table <code>public.security_row_level_policy_</code>.
     */
    public static final SecurityRowLevelPolicy_ SECURITY_ROW_LEVEL_POLICY_ = es.eci.catalog.model.tables.SecurityRowLevelPolicy_.SECURITY_ROW_LEVEL_POLICY_;

    /**
     * The table <code>public.security_user_</code>.
     */
    public static final SecurityUser_ SECURITY_USER_ = es.eci.catalog.model.tables.SecurityUser_.SECURITY_USER_;

    /**
     * The table <code>public.teaching_center_</code>.
     */
    public static final TeachingCenter_ TEACHING_CENTER_ = es.eci.catalog.model.tables.TeachingCenter_.TEACHING_CENTER_;
}
