/*
 * This file is generated by jOOQ.
*/
package es.eci.catalog.model;


import es.eci.catalog.model.udt.Person_;

import javax.annotation.Generated;


/**
 * Convenience access to all UDTs in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UDTs {

    /**
     * The type <code>public.person_</code>
     */
    public static Person_ PERSON_ = es.eci.catalog.model.udt.Person_.PERSON_;
}
